/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsocket;

import java.awt.Color;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static mathsocket.Jugador2.datoSalida;
import static mathsocket.Jugador2.mensaje;

/**
 *
 * @author lujor
 */
public class Jugador1 extends javax.swing.JFrame {
    
    static Imagenes imagenes = new Imagenes();
    static int valorDado = 0;
    static String mensaje = "";
    static ServerSocket serverSocket;
    static Socket socket;
    static DataInputStream datoEntrada;
    static DataOutputStream datoSalida;

    /**
     * Creates new form Jugador1
     */
    public Jugador1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Nombre1 = new javax.swing.JTextField();
        buttonJugar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        AvisoNombre = new javax.swing.JLabel();
        buttonInstru = new javax.swing.JButton();
        EsperarJugador = new javax.swing.JLabel();
        PanelJuego = new javax.swing.JPanel();
        fichaJugador1 = new javax.swing.JLabel();
        fichaJugador2 = new javax.swing.JLabel();
        CInicio = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        C9 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        CFinal = new javax.swing.JLabel();
        C10 = new javax.swing.JLabel();
        C11 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C15 = new javax.swing.JLabel();
        C13 = new javax.swing.JLabel();
        C12 = new javax.swing.JLabel();
        C14 = new javax.swing.JLabel();
        buttonDado = new javax.swing.JLabel();
        Dado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        setPreferredSize(new java.awt.Dimension(600, 635));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(0, 51, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setFocusable(false);
        MainPanel.setName(""); // NOI18N
        MainPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        Nombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Nombre1.setForeground(new java.awt.Color(153, 153, 153));
        Nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nombre1.setText("Ingresar nombre (max 10 caracteres)");
        Nombre1.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        Nombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Nombre1MousePressed(evt);
            }
        });
        Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1ActionPerformed(evt);
            }
        });

        buttonJugar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        buttonJugar.setText("Jugar");
        buttonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJugarAction(evt);
            }
        });

        buttonSalir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirAction(evt);
            }
        });

        AvisoNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonInstru.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        buttonInstru.setText("Intrucciones");
        buttonInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInstruAction(evt);
            }
        });

        EsperarJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInstru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(EsperarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvisoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AvisoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(EsperarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(buttonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(buttonInstru, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelJuego.setBackground(new java.awt.Color(0, 153, 153));
        PanelJuego.setPreferredSize(new java.awt.Dimension(600, 600));
        PanelJuego.setLayout(null);

        fichaJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jugador 1.png"))); // NOI18N
        fichaJugador1.setText("sdad");
        PanelJuego.add(fichaJugador1);
        fichaJugador1.setBounds(160, 50, 40, 40);

        fichaJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jugador 2.png"))); // NOI18N
        fichaJugador2.setText("jLabel1");
        PanelJuego.add(fichaJugador2);
        fichaJugador2.setBounds(220, 50, 40, 40);

        CInicio.setBackground(new java.awt.Color(204, 0, 204));
        CInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        CInicio.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(CInicio);
        CInicio.setBounds(10, 135, 130, 87);

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C2.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C2);
        C2.setBounds(158, 135, 130, 87);

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C3.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C3);
        C3.setBounds(302, 135, 130, 87);

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C8.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C8);
        C8.setBounds(14, 255, 130, 87);

        C9.setBackground(new java.awt.Color(204, 0, 204));
        C9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C9.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C9);
        C9.setBounds(10, 371, 130, 87);

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C7.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C7);
        C7.setBounds(162, 255, 130, 87);

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C6.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C6);
        C6.setBounds(306, 255, 130, 87);

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C4.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C4);
        C4.setBounds(442, 135, 130, 87);

        CFinal.setBackground(new java.awt.Color(204, 0, 204));
        CFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - fin2.png"))); // NOI18N
        CFinal.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(CFinal);
        CFinal.setBounds(10, 487, 130, 87);

        C10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C10.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C10);
        C10.setBounds(168, 371, 130, 87);

        C11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C11.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C11);
        C11.setBounds(316, 371, 130, 87);

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C5.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C5);
        C5.setBounds(446, 255, 130, 87);

        C15.setBackground(new java.awt.Color(204, 0, 204));
        C15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C15.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C15);
        C15.setBounds(170, 487, 130, 87);

        C13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C13.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C13);
        C13.setBounds(457, 487, 130, 87);

        C12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C12.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C12);
        C12.setBounds(454, 371, 130, 87);

        C14.setBackground(new java.awt.Color(204, 0, 204));
        C14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casilla - inicio2.png"))); // NOI18N
        C14.setPreferredSize(new java.awt.Dimension(150, 50));
        PanelJuego.add(C14);
        C14.setBounds(318, 487, 130, 87);

        buttonDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/interrogation.png"))); // NOI18N
        buttonDado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDadoMouseClicked(evt);
            }
        });
        PanelJuego.add(buttonDado);
        buttonDado.setBounds(480, 22, 80, 80);

        Dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DadoZero.png"))); // NOI18N
        PanelJuego.add(Dado);
        Dado.setBounds(26, 11, 83, 83);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre1ActionPerformed

    private void buttonJugarAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJugarAction

        String Jugador1 = Nombre1.getText();
        int espacios = 0;
        
        if (Jugador1.contentEquals("") || Jugador1.length() >= 10) {
            AvisoNombre.setText("¡Nombre no válido!");
            return;
        }
        for (int i = 0; i <= Jugador1.length() - 1; i++) {
            String letra = String.valueOf(Jugador1.charAt(i));
            if (!letra.equals(" ")) {
                espacios++;
            }
        }
        if (espacios == 0) {
            AvisoNombre.setText("¡Nombre Vacío!");
            return;
        } else {
            fichaJugador1.setLocation(CInicio.getX(),CInicio.getY());
            fichaJugador2.setLocation(CInicio.getX()+20,CInicio.getY());
            EsperarJugador.setText("Esperando Jugador...");

        }


    }//GEN-LAST:event_buttonJugarAction

    private void buttonSalirAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirAction
        System.exit(0);
    }//GEN-LAST:event_buttonSalirAction

    private void buttonInstruAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInstruAction
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInstruAction

    private void Nombre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre1MousePressed
        Nombre1.setText("");
        Nombre1.setForeground(Color.black);
    }//GEN-LAST:event_Nombre1MousePressed

    private void buttonDadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDadoMouseClicked
        try {
            Random numDado = new Random();
            int num = numDado.nextInt(4) + 1;
            if (valorDado == 0) {
                System.out.println("si pasa");
                String digito = String.valueOf(num);
                datoSalida.writeUTF(digito);
                buttonDado.setEnabled(false);
                valorDado = 1;
                switch (num) {
                    case 1:

                        Dado.setIcon(imagenes.img1);
                        break;

                    case 2:

                        Dado.setIcon(imagenes.img2);
                        break;

                    case 3:

                        Dado.setIcon(imagenes.img3);
                        break;

                    case 4:

                        Dado.setIcon(imagenes.img4);
                        break;
                }
            } else {
                datoSalida.writeUTF("es tu turno");
                switch (num) {
                    case 1:

                        Dado.setIcon(imagenes.img1);
                        break;

                    case 2:

                        Dado.setIcon(imagenes.img2);
                        break;

                    case 3:

                        Dado.setIcon(imagenes.img3);
                        break;

                    case 4:

                        Dado.setIcon(imagenes.img4);
                        break;
                }
                buttonDado.setEnabled(false);
            }
            System.out.println(num);
        } catch (IOException ex) {
            Logger.getLogger(Jugador1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonDadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (java.lang.NullPointerException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador1().setVisible(true);
            }
        });

        try {
            serverSocket = new ServerSocket(1201);
            socket = serverSocket.accept();
            datoEntrada = new DataInputStream(socket.getInputStream());
            datoSalida = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(Jugador1.class.getName()).log(Level.SEVERE, null, ex);
        }
        JLabel[] casillas = new JLabel[]{C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15};
        
        while (true) {
            if (mensaje.equals("casilla")) {
                ListCasillas coordenadas = new ListCasillas();
                for (int i = 0; i <= casillas.length; i++) {
                    if (i != casillas.length) {
                        try {
                            mensaje = datoEntrada.readUTF();
                        } catch (IOException ex) {
                            Logger.getLogger(Jugador1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        int index = Integer.parseInt(mensaje);
                        JLabel casilla = casillas[i];
                        switch (index) {
                            case 1:
                                coordenadas.insertLast(casilla.getX(), casilla.getY());
                                casilla.setIcon(imagenes.CasillaReto);
                                break;
                            case 2:
                                coordenadas.insertLast(casilla.getX(), casilla.getY());
                                casilla.setIcon(imagenes.CasillaTrampa);
                                break;
                            case 3:
                                coordenadas.insertLast(casilla.getX(), casilla.getY());
                                casilla.setIcon(imagenes.CasillaTunel);
                                break;
                        }
                    } else {
                        coordenadas.insertLast(CFinal.getX(), CFinal.getY());
                    }
                }
            } else {
                try {
                    mensaje = datoEntrada.readUTF();
                } catch (IOException ex) {
                    Logger.getLogger(Jugador1.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (mensaje.equals("iniciar")) {
                    MainPanel.setVisible(false);
                    PanelJuego.setVisible(true);
                    mensaje = "";
                }
                if (mensaje.equals("otra vez")) {
                    buttonDado.setEnabled(true);
                    Dado.setIcon(imagenes.CasillaZero);
                    valorDado = 0;

                } else if (mensaje.equals("es tu turno")) {
                    buttonDado.setEnabled(true);
                    valorDado = 1;
                }
            }

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvisoNombre;
    private static javax.swing.JLabel C10;
    private static javax.swing.JLabel C11;
    private static javax.swing.JLabel C12;
    private static javax.swing.JLabel C13;
    private static javax.swing.JLabel C14;
    private static javax.swing.JLabel C15;
    private static javax.swing.JLabel C2;
    private static javax.swing.JLabel C3;
    private static javax.swing.JLabel C4;
    private static javax.swing.JLabel C5;
    private static javax.swing.JLabel C6;
    private static javax.swing.JLabel C7;
    private static javax.swing.JLabel C8;
    private static javax.swing.JLabel C9;
    private static javax.swing.JLabel CFinal;
    private javax.swing.JLabel CInicio;
    private static javax.swing.JLabel Dado;
    private static javax.swing.JLabel EsperarJugador;
    private static javax.swing.JPanel MainPanel;
    private javax.swing.JTextField Nombre1;
    private static javax.swing.JPanel PanelJuego;
    private static javax.swing.JLabel buttonDado;
    private javax.swing.JButton buttonInstru;
    private javax.swing.JButton buttonJugar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel fichaJugador1;
    private javax.swing.JLabel fichaJugador2;
    // End of variables declaration//GEN-END:variables
}
